name: Analyze on SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  analyze-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Analyze on SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=ESrebuff_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=esrebuff
            -Dsonar.sources=./front
            -Dsonar.exclusions=**/back/**/*
            -Dsonar.projectBaseDir=./front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
