name: Analyze on SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  analyze-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Analyze on SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -X
            -Dsonar.projectKey=ESrebuff_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=esrebuff
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
