name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-back:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./back
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and test with Maven
      run: mvn clean install
    - name: Upload JaCoCo coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-coverage-report
        path: back/target/site/jacoco
        
  build-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
        run:
          working-directory: ./front
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm i -g @angular/cli@14
    - run: npm run build
    - run: ng test --browsers ChromeHeadless --watch=false --code-coverage
    - name: Upload karma coverage report artifact
          uses: actions/upload-artifact@v3
          with:
            name: karma-coverage-report
            path: front/coverage/bobapp